# Generated by Django 4.0.1 on 2022-02-01 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sistema.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('monto_apertura', models.IntegerField(default=0)),
                ('monto_cierre', models.IntegerField(default=0)),
                ('efectivo', models.IntegerField(default=0)),
                ('tarjeta_debito', models.IntegerField(default=0)),
                ('tarjeta_credito', models.IntegerField(default=0)),
                ('vale_cobrado', models.IntegerField(default=0)),
                ('vale_cobrar', models.IntegerField(default=0)),
                ('monto_500', models.IntegerField(default=0)),
                ('monto_1000', models.IntegerField(default=0)),
                ('monto_2000', models.IntegerField(default=0)),
                ('monto_5000', models.IntegerField(default=0)),
                ('monto_10000', models.IntegerField(default=0)),
                ('monto_20000', models.IntegerField(default=0)),
                ('monto_50000', models.IntegerField(default=0)),
                ('monto_100000', models.IntegerField(default=0)),
                ('transferencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('documento', models.CharField(max_length=100, verbose_name='RUC/CI')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100)),
                ('condicion', models.PositiveSmallIntegerField(choices=[(0, 'CONTADO'), (1, 'CREDITO')], default=0)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guarnicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('costo_extra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemEnsalada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('costo_extra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=500)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tyra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('costo_extra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.compra')),
            ],
        ),
        migrations.CreateModel(
            name='PagoChequeDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cheque', models.CharField(max_length=100)),
                ('pago_cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pagocheque')),
            ],
        ),
        migrations.AddField(
            model_name='pagocheque',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.IntegerField()),
                ('codigo_barra', models.CharField(max_length=100)),
                ('codigo_manual', models.CharField(max_length=100)),
                ('precio_venta', models.IntegerField()),
                ('observacion', models.TextField()),
                ('iva', models.PositiveSmallIntegerField(choices=[(0, 'Exentas'), (5, 'IVA 5'), (10, 'IVA 10')])),
                ('usa_stock', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to=sistema.models.path_and_rename, verbose_name='foto')),
                ('tipo_articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.tipoarticulo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.unidadmedida')),
            ],
        ),
    ]
