# Generated by Django 4.0.1 on 2022-02-01 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aperturacaja',
            options={'ordering': ['-fecha'], 'verbose_name': 'Apertura de caja', 'verbose_name_plural': 'Apertura de caja'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['descripcion'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Otro gasto', 'verbose_name_plural': 'Otros Gastos'},
        ),
        migrations.AlterModelOptions(
            name='guarnicion',
            options={'ordering': ['descripcion'], 'verbose_name': 'Guarnicion', 'verbose_name_plural': 'Guarnicion'},
        ),
        migrations.AlterModelOptions(
            name='itemensalada',
            options={'ordering': ['descripcion'], 'verbose_name': 'Item ensalada', 'verbose_name_plural': 'Item ensalada'},
        ),
        migrations.AlterModelOptions(
            name='pagocheque',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pago cheque', 'verbose_name_plural': 'Pago cheque'},
        ),
        migrations.AlterModelOptions(
            name='pagochequedetalle',
            options={'verbose_name': 'Pago cheque detalle', 'verbose_name_plural': 'Pago cheque detalle'},
        ),
        migrations.AlterModelOptions(
            name='pagoproveedor',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pago a proveedor', 'verbose_name_plural': 'Pagos a proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'verbose_name': 'Tipo de artículo', 'verbose_name_plural': 'Tipos de artículo'},
        ),
        migrations.AlterModelOptions(
            name='tipoventa',
            options={'ordering': ['descripcion'], 'verbose_name': 'Tipo de venta', 'verbose_name_plural': 'Tipos de venta'},
        ),
        migrations.AlterModelOptions(
            name='tyra',
            options={'ordering': ['descripcion'], 'verbose_name': 'Tyra', 'verbose_name_plural': 'Tyra'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['descripcion'], 'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
