# Generated by Django 4.0.1 on 2022-02-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_aperturacaja_options_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagochequedetalle',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
